spring:
  application:
    name: user-module
  datasource:
    url: jdbc:postgresql://localhost:5432/PoiCore
    username: PoiCore
    password: PoiCorePassword
  liquibase:
    change-log: classpath:db/changelog/user-master.yml
    enabled: true
  threads:
    virtual:
      enabled: true
  cloud:
    aws:
      region:
        static: 'us-east-1'
      credentials:
#        access-key: 'AKIA5O2ROCODX7NTRAVA'
#        secret-key: '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'
verification:
  required: false
