version: '3.5'

services:
  postgresql:
    container_name: postgresql
    image: postgres:13.1
    environment:
      - POSTGRES_USER=PoiCore
      - POSTGRES_PASSWORD=PoiCorePassword
    ports:
      - 5432:5432
    networks:
      - poi-core
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs
      - DEBUG=1
    networks:
      - poi-core
networks:
  poi-core:
    name: poi-core
    driver: bridge
